name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/your_binary_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_TOKEN }}
        env:
          CARGO_REGISTERY_TOKEN: ${{ secrets.CARGO_TOKEN }}
