name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-tap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone Homebrew Tap repository
        run: |
          git clone https://github.com/hackerchai/homebrew-tap.git
          cd homebrew-tap
          git checkout -b update-formula

      - name: Download and Calculate SHA256
        run: |
          version=${{ github.event.release.tag_name }}
          curl -LO https://github.com/hackerchai/dylib-installer/releases/download/$version/dylib_installer-macos-amd64
          curl -LO https://github.com/hackerchai/dylib-installer/releases/download/$version/dylib_installer-macos-arm64
          sha256_amd64=$(sha256sum dylib_installer-macos-amd64 | awk '{print $1}')
          sha256_arm64=$(sha256sum dylib_installer-macos-arm64 | awk '{print $1}')

          echo "class DylibInstaller < Formula" > homebrew-tap/dylib-installer.rb
          echo "  desc \"Tool to install dylib files and header to system library path written in rust.\"" >> homebrew-tap/dylib-installer.rb
          echo "  homepage \"https://github.com/hackerchai/dylib-installer\"" >> homebrew-tap/dylib-installer.rb
          echo "  license \"gpl-3.0\"" >> homebrew-tap/dylib-installer.rb
          echo "  version \"$version\"" >> homebrew-tap/dylib-installer.rb
          echo "" >> homebrew-tap/dylib-installer.rb
          echo "  if Hardware::CPU.intel?" >> homebrew-tap/dylib-installer.rb
          echo "    url \"https://github.com/hackerchai/dylib-installer/releases/download/$version/dylib_installer-macos-amd64\"" >> homebrew-tap/dylib-installer.rb
          echo "    sha256 \"$sha256_amd64\"" >> homebrew-tap/dylib-installer.rb
          echo "  elsif Hardware::CPU.arm?" >> homebrew-tap/dylib-installer.rb
          echo "    url \"https://github.com/hackerchai/dylib-installer/releases/download/$version/dylib_installer-macos-arm64\"" >> homebrew-tap/dylib-installer.rb
          echo "    sha256 \"$sha256_arm64\"" >> homebrew-tap/dylib-installer.rb
          echo "  end" >> homebrew-tap/dylib-installer.rb
          echo "" >> homebrew-tap/dylib-installer.rb
          echo "  def install" >> homebrew-tap/dylib-installer.rb
          echo "    bin.install \"dylib-installer\"" >> homebrew-tap/dylib-installer.rb
          echo "  end" >> homebrew-tap/dylib-installer.rb
          echo "" >> homebrew-tap/dylib-installer.rb
          echo "  test do" >> homebrew-tap/dylib-installer.rb
          echo "    system \"\#{bin}/dylib-installer\", \"--help\"" >> homebrew-tap/dylib-installer.rb
          echo "  end" >> homebrew-tap/dylib-installer.rb
          echo "end" >> homebrew-tap/dylib-installer.rb

      - name: Commit and Push changes
        run: |
          cd homebrew-tap
          git add dylib-installer.rb
          git commit -m "Update dylib-installer formula to version ${{ github.event.release.tag_name }}"
          git push origin update-formula

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: "Update dylib-installer formula to version ${{ github.event.release.tag_name }}"
          branch: update-formula
          title: "Update dylib-installer formula to version ${{ github.event.release.tag_name }}"
          body: "This PR updates the dylib-installer formula to version ${{ github.event.release.tag_name }}."
          labels: "auto-update"
